package com.chairforce.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "Users")
public class User {

    @DynamoDBHashKey(attributeName = "UserId")
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute(attributeName = "FirstName")
    private String firstName;

    @DynamoDBAttribute(attributeName = "LastName")
    private String lastName;

    @DynamoDBAttribute(attributeName = "Age")
    private int age;

    @DynamoDBAttribute(attributeName = "Email")
    private String email;


}
